# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LSDRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateTimeField(verbose_name='date published')),
                ('run_root_date', models.FloatField()),
                ('run_tips_date', models.FloatField()),
                ('run_constraints', models.BooleanField()),
                ('run_variance', models.BooleanField()),
                ('run_seq_length', models.IntegerField()),
                ('run_param_variance', models.FloatField()),
                ('run_rooting_method', models.CharField(max_length=10)),
                ('run_rate_lower_bound', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RunOutGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxon_name', models.CharField(max_length=300)),
                ('lsd_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lsd.LSDRun')),
            ],
        ),
        migrations.CreateModel(
            name='RunTaxonDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxon_name', models.CharField(max_length=300)),
                ('taxon_date', models.FloatField()),
                ('lsd_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lsd.LSDRun')),
            ],
        ),
        migrations.CreateModel(
            name='RunTrees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_newick', models.TextField()),
                ('tree_subst_rate', models.FloatField()),
                ('lsd_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lsd.LSDRun')),
            ],
        ),
    ]
