# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsdrun',
            name='run_constraints',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lsdrun',
            name='run_param_variance',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='lsdrun',
            name='run_rate_lower_bound',
            field=models.FloatField(default=1e-05),
        ),
        migrations.AlterField(
            model_name='lsdrun',
            name='run_root_date',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lsdrun',
            name='run_seq_length',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='lsdrun',
            name='run_tips_date',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='lsdrun',
            name='run_variance',
            field=models.BooleanField(default=False),
        ),
    ]
