# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsd', '0002_auto_20160201_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsdrun',
            name='run_name',
            field=models.CharField(default='No Name', max_length=100),
        ),
    ]
