# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsd', '0003_lsdrun_run_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsdrun',
            name='run_date',
            field=models.DateTimeField(verbose_name='date of run'),
        ),
    ]
