# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsd', '0004_auto_20160201_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_subst_rate', models.FloatField()),
                ('result_root_date', models.FloatField()),
                ('result_newick', models.TextField()),
                ('result_date_newick', models.TextField()),
                ('result_nexus', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='runtrees',
            name='tree_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resulttree',
            name='run_tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lsd.RunTrees'),
        ),
    ]
